/**
 * @description Animates a packet icon moving from the origin network object to the destination
 * network object on the board. Skips animation if the packet was generated by the destination
 * device itself, or if ARP traffic is set to be ignored and the packet is ARP.
 * @param {string} originObject - DOM id of the sending network object.
 * @param {string} destinationObjectId - DOM id of the receiving network object.
 * @param {Object} packet - Packet instance describing the transmission.
 * @param {string} packet.protocol - Protocol name (e.g. "arp", "icmp", "dhcp", "tcp", "dns").
 * @param {string} packet.type - Packet type within the protocol (e.g. "request", "reply", "discover").
 * @param {string} packet.origin_ip - Source IP address of the packet.
 * @returns {Promise<void>}
 */
async function visualize(originObject, destinationObjectId, packet) {

    if (getAvailableIps(destinationObjectId).includes(packet.origin_ip)) return; //the packet is generated by the same device

    const $originObject = document.getElementById(originObject);
    const $destinationObject = document.getElementById(destinationObjectId);

    const packetTypeMap = {
        "arp-request": "broadcast",
        "arp-reply": "unicast",
        "dhcp-discover": "dhcp",
        "dhcp-request": "dhcp",
        "dhcp-offer": "dhcp",
        "dhcp-ack": "dhcp",
        "tcp-syn": "tcp",
        "tcp-syn-ack": "tcp",
        "tcp-syn-ack-reply": "tcp",
        "dns-request": "dns",
        "dns-reply": "dns",
    };

    if (ignoreArpTraffic && packet.protocol === "arp") return;

    const type = packetTypeMap[`${packet.protocol}-${packet.type}`] || "unicast";

    await movePacket(
        $originObject.style.left,
        $originObject.style.top,
        $destinationObject.style.left,
        $destinationObject.style.top,
        type
    );

}
